version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
