spring:
  application:
    name: reagent_order
  datasource:
    url: jdbc:postgresql://localhost:5432/main
    username: sa
    password: pass1234
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG

