spring:
  application:
    name: reagent_order
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/main}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:pass1234}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.security: DEBUG
    org.jooq.tools.LoggerListener: DEBUG
    io.jsonwebtoken: DEBUG

