spring:
  application:
    name: jooq
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/main}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:pass1234}
    driver-class-name: org.postgresql.Driver

jooq:
  sql-dialect: POSTGRES # jOOQで使用するデータベースのSQL方言
