spring:
  application:
    name: migration
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/main}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:pass1234}
    driver-class-name: org.postgresql.Driver

flyway:
  url: ${JDBC_URL:jdbc:postgresql://localhost:5432/main}
  user: ${DB_USER:sa}
  password: ${DB_PASSWORD:pass1234}
  locations: ${FLYWAY_LOCATIONS:filesystem:src/main/resources/db/migration}
